### ISSUE TITLE
test-net /archway integration

### ISSUE THREAD

**Issue by wotori** [wotori-studio/Landing#10]
dockerfile with testnet for development purpose.
This task should be more detailed along with the [archway](http://archway.io/) research.

to read:
[cosmos-introducing-archway](https://blog.archway.io/arch-into-cosmos-introducing-archway-2447ef5df0c5?gi=3a48a5ad383e)

**Comment by wotori** [comment]
I found that it's "Originally forked from the [cosmos/gaia](https://github.com/cosmos/gaia) repository.", so the archway as it is - adding the layer of "developers reward system" to gaia, kind of upgrade or feature.

**Comment by wotori** [comment]
there is the archway-cli
```% npm install -g @archwayhq/cli```
```% archway```

**Comment by wotori** [comment]
for ```% archway new``` we have to [setup](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) ssh.
[This](https://github.com/cargo-generate/cargo-generate/issues/418) pointed me to the Idea how to force archway build project with "cargo generate".

**Comment by goodza** [comment]
Key features to include a generic NFT marketplace smart contract, listing CW721 tokens for sale for any CW20 token, buying CW721 tokens with CW20 tokens, trading any CW721 token with any other CW721, and any additional marketplace capabilities you’re keen to experiment with (auctions, fractionalization, royalties, etc.)

**Comment by goodza** [comment]
Great reference from previous HackAtom (V)
https://blockscape-network.medium.com/hackatom-v-nft-marketplace-smart-contract-795b743a7738
https://github.com/BlockscapeNetwork/hackatom_v/tree/master/contracts/marketplace
